import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationUtil extends ChangeNotifier {
  static const String _keyLang = "selected_language";
  String _selectedLanguage = "en";

  String get selectedLanguage => _selectedLanguage;

  LocalizationUtil() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _selectedLanguage = prefs.getString(_keyLang) ?? "en";
    notifyListeners();
  }

  Future<void> saveLanguage(String lang) async {
    _selectedLanguage = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_keyLang, lang);
    notifyListeners();
  }

  static const List<Map<String, String>> supportedLanguages = [
    {"label": "🇺🇸 English", "code": "en", "name": "English"},
    {"label": "🇫🇷 Français", "code": "fr", "name": "French"},
    {"label": "🇪🇸 Español", "code": "es", "name": "Spanish"},
    {"label": "🇹🇭 ไทย", "code": "th", "name": "Thai"},
    {"label": "🇵🇹 Português", "code": "pt", "name": "Portuguese"},
    {"label": "🇭🇹 Kreyòl Ayisyen", "code": "ht", "name": "Haitian Creole"},
    {"label": "🇳🇱 Nederlands", "code": "nl", "name": "Dutch"},
    {"label": "🇮🇱 עברית", "code": "he", "name": "Hebrew"},
    {"label": "🇸🇦 العربية", "code": "ar", "name": "Arabic"}
  ];

  static const Map<String, Map<String, String>> _translations = {
    "en": {
      "app_name": "WalletCards",
      "my_cards": "My Cards",
      "apply_new": "Apply New",
      "logout": "Logout",
      "settings": "Settings",
      "language": "Language",
      "select_language": "Select Language",
      "action_required": "Action Required",
      "awaiting_payment": "Awaiting Payment",
      "pay_now": "Pay Now",
      "apply_for_card": "Apply for New Card",
      "back": "Back",
      "current_balance": "Current Balance",
      "transactions": "Transactions",
      "deposits": "Deposits",
      "deposit_crypto": "Deposit Crypto",
      "address_copied": "Address copied",
      "card_payment": "Card Payment",
      "total_to_pay": "Total Amount to Pay",
      "deposit_address": "Deposit Address",
      "i_have_paid": "I Have Paid",
      "login": "Login",
      "register": "Register",
      "email": "Email",
      "password": "Password",
      "dont_have_account": "Don't have an account? Register",
      "already_have_account": "Already have an account? Login",
      "user_not_found": "User Not Found",
      "3ds_auth": "3DS Authentication",
      "merchant": "Merchant",
      "amount": "Amount",
      "approve": "Approve",
      "reject": "Reject",
      "approved": "Approved",
      "verify_details": "Please verify the transaction details before approving.",
      "disclaimer_non_usdc": "For non USDC coins deposit fees 2% plus network fees apply. Coins to USDC exchange rates at actual's.",
      "disclaimer_exact_amount": "Kindly pay the exact amount only. Lower amounts may cause loss of funds. \$5.00 will remain as your initial card balance.",
      "step_fee": "There is a fee for new cards of \$%s out of which \$5 will remain as your card balance. Confirm to continue.",
      "step_first_name": "What will be the first name on the card?",
      "step_last_name": "What will be the last name on the card?",
      "step_dob": "What is your date of birth?",
      "step_country_code": "What is your country phonecode?",
      "step_phone": "What is your phone number?",
      "step_address": "What is your address?",
      "step_city": "What is your city?",
      "step_state": "What is your state?",
      "step_country": "What is your country?",
      "step_postal": "What is your postal code?",
      "thank_you_apply": "Thank you, I am going to apply the card for you now.",
      "invalid_phone": "Invalid input. The phone number should not include any spaces or special characters. Please re-enter your phone number.",
      "confirm": "Confirm",
      "cancel": "Cancel",
      "apply": "Apply",
      "done": "Done",
      "search_country": "Search Country",
      "search_country_code": "Search Country Code",
      "select_dob": "Select Date of Birth",
      "welcome_registered": "Welcome! Are you already registered?",
      "great_email": "Great! Please enter your email address.",
      "now_password": "Now, please enter your password.",
      "invalid_password_format": "Password must be 6 alphanumeric characters. Please try again.",
      "login_failed": "Login failed",
      "enter_email": "Enter email...",
      "enter_password": "Enter password...",
      "reset_link_sent": "If this email is registered, a password reset link has been sent.",
      "enter_email_first": "Please enter your email address in the chat first.",
      "forgot_password": "Forgot Password?",
      "yes": "Yes",
      "no": "No",
      "create_account": "Create Account",
      "let_create_account": "Let's create your account! Please enter your email address.",
      "choose_password": "Great! Now, please choose a password (6 alphanumeric characters).",
      "registration_failed": "Registration failed",
      "card_details": "Card Details",
      "cardholder": "Cardholder",
      "expiry": "Expiry",
      "billing_address": "Billing Address",
      "crypto_deposit": "Crypto Deposit",
      "today": "Today",
      "yesterday": "Yesterday",
      "approval_failed": "Approval failed. Please try again.",
      "register_or_forgot": "Register or Forgot Password?",
      "virtual_card_for": "Virtual Card for",
      "splash_msg_1": "Virtual card issuing at its best",
      "splash_msg_2": "We are available in 100+ countries",
      "splash_msg_3": "Add to wallets Google pay and Apple pay(Comingsoon)",
      "type_answer": "Type your answer...",
      "virtual_mastercards": "Virtual MasterCards"
    },
    "fr": {
      "app_name": "WalletCards",
      "my_cards": "Mes Cartes",
      "apply_new": "Nouvelle Carte",
      "logout": "Déconnexion",
      "settings": "Paramètres",
      "language": "Langue",
      "select_language": "Choisir la Langue",
      "action_required": "Action Requise",
      "awaiting_payment": "En Attente de Paiement",
      "pay_now": "Payer Maintenant",
      "apply_for_card": "Demander une Nouvelle Carte",
      "back": "Retour",
      "current_balance": "Solde Actuel",
      "transactions": "Transactions",
      "deposits": "Dépôts",
      "deposit_crypto": "Déposer de la Crypto",
      "address_copied": "Adresse copiée",
      "card_payment": "Paiement par Carte",
      "total_to_pay": "Montant Total à Payer",
      "deposit_address": "Adresse de Dépôt",
      "i_have_paid": "J'ai Payé",
      "login": "Connexion",
      "register": "S'inscrire",
      "email": "Email",
      "password": "Mot de Passe",
      "dont_have_account": "Pas de compte ? S'inscrire",
      "already_have_account": "Déjà un compte ? Connexion",
      "user_not_found": "Utilisateur Non Trouvé",
      "3ds_auth": "Authentification 3DS",
      "merchant": "Marchand",
      "amount": "Montant",
      "approve": "Approuver",
      "reject": "Rejeter",
      "approved": "Approuvé",
      "verify_details": "Veuillez vérifier les détails de la transaction avant d'approuver.",
      "disclaimer_non_usdc": "Pour les pièces non USDC, des frais de dépôt de 2% plus les frais de réseau s'appliquent. Taux de change des pièces en USDC au réel.",
      "disclaimer_exact_amount": "Veuillez payer exactement le montant indiqué. Des montants inférieurs peuvent entraîner une perte de fonds. 5,00 \$ resteront comme solde initial de votre carte.",
      "step_fee": "Il y a des frais pour les nouvelles cartes de %s \$ dont 5 \$ resteront comme solde de votre carte. Confirmez pour continuer.",
      "step_first_name": "Quel sera le prénom sur la carte ?",
      "step_last_name": "Quel sera le nom de famille sur la carte ?",
      "step_dob": "Quelle est votre date de naissance ?",
      "step_country_code": "Quel est l'indicatif téléphonique de votre pays ?",
      "step_phone": "Quel est votre numéro de téléphone ?",
      "step_address": "Quelle est votre adresse ?",
      "step_city": "Quelle est votre ville ?",
      "step_state": "Quel est votre état/province ?",
      "step_country": "Quel est votre pays ?",
      "step_postal": "Quel est votre code postal ?",
      "thank_you_apply": "Merci, je vais maintenant demander la carte pour vous.",
      "invalid_phone": "Entrée non valide. Le numéro de téléphone ne doit pas inclure d'espaces ou de caractères spéciaux. Veuillez saisir à nouveau votre numéro de téléphone.",
      "confirm": "Confirmer",
      "cancel": "Annuler",
      "apply": "Appliquer",
      "done": "Terminé",
      "search_country": "Rechercher un Pays",
      "search_country_code": "Rechercher un Indicatif",
      "select_dob": "Sélectionner la Date de Naissance",
      "welcome_registered": "Bienvenue ! Êtes-vous déjà inscrit ?",
      "great_email": "Génial ! Veuillez entrer votre adresse e-mail.",
      "now_password": "Maintenant, veuillez entrer votre mot de passe.",
      "invalid_password_format": "Le mot de passe doit comporter 6 caractères alphanumériques. Veuillez réessayer.",
      "login_failed": "Échec de la connexion",
      "enter_email": "Entrer l'e-mail...",
      "enter_password": "Entrer le mot de passe...",
      "reset_link_sent": "Si cet e-mail est enregistré, un lien de réinitialisation de mot de passe a été envoyé.",
      "enter_email_first": "Veuillez d'abord entrer votre adresse e-mail dans le chat.",
      "forgot_password": "Mot de passe oublié ?",
      "yes": "Oui",
      "no": "Non",
      "create_account": "Créer un compte",
      "let_create_account": "Créons votre compte ! Veuillez entrer votre adresse e-mail.",
      "choose_password": "Génial ! Maintenant, veuillez choisir un mot de passe (6 caractères alphanumériques).",
      "registration_failed": "Échec de l'enregistrement",
      "card_details": "Détails de la carte",
      "cardholder": "Titulaire",
      "expiry": "Expire le",
      "billing_address": "Adresse de facturation",
      "crypto_deposit": "Dépôt de Crypto",
      "today": "Aujourd'hui",
      "yesterday": "Hier",
      "approval_failed": "Échec de l'approbation. Veuillez réessayer.",
      "register_or_forgot": "S'inscrire ou Mot de passe oublié ?",
      "virtual_card_for": "Carte virtuelle pour",
      "splash_msg_1": "L'émission de cartes virtuelles à son meilleur",
      "splash_msg_2": "Nous sommes disponibles dans plus de 100 pays",
      "splash_msg_3": "Ajouter aux portefeuilles Google Pay et Apple Pay (Bientôt disponible)",
      "type_answer": "Tapez votre réponse...",
      "virtual_mastercards": "MasterCards Virtuelles"
    },
    "es": {
      "app_name": "WalletCards",
      "my_cards": "Mis Tarjetas",
      "apply_new": "Solicitar Nueva",
      "logout": "Cerrar sesión",
      "settings": "Ajustes",
      "language": "Idioma",
      "select_language": "Seleccionar Idioma",
      "action_required": "Acción Requerida",
      "awaiting_payment": "Esperando Pago",
      "pay_now": "Pagar Ahora",
      "apply_for_card": "Solicitar Nueva Tarjeta",
      "back": "Atrás",
      "current_balance": "Saldo Actual",
      "transactions": "Transacciones",
      "deposits": "Depósitos",
      "deposit_crypto": "Depositar Cripto",
      "address_copied": "Dirección copiada",
      "card_payment": "Pago con Tarjeta",
      "total_to_pay": "Monto Total a Pagar",
      "deposit_address": "Dirección de Depósito",
      "i_have_paid": "He Pagado",
      "login": "Iniciar sesión",
      "register": "Registrarse",
      "email": "Correo electrónico",
      "password": "Contraseña",
      "dont_have_account": "¿No tienes cuenta? Regístrate",
      "already_have_account": "¿Ya tienes cuenta? Inicia sesión",
      "user_not_found": "Usuario No Encontrado",
      "3ds_auth": "Autenticación 3DS",
      "merchant": "Comercio",
      "amount": "Monto",
      "approve": "Aprobar",
      "reject": "Rechazar",
      "approved": "Aprobado",
      "verify_details": "Por favor verifique los detalles de la transacción antes de aprobar.",
      "disclaimer_non_usdc": "Para monedas que no sean USDC, se aplican tarifas de depósito del 2% más las de la red. Tasas de cambio a USDC al valor real.",
      "disclaimer_exact_amount": "Por favor pague el monto exacto solamente. Montos menores pueden causar pérdida de fondos. \$5.00 permanecerán como saldo inicial.",
      "step_fee": "Hay una tarifa por tarjetas nuevas de \$%s de los cuales \$5 permanecerán como saldo. Confirme para continuar.",
      "step_first_name": "¿Cuál será el primer nombre en la tarjeta?",
      "step_last_name": "¿Cuál será el apellido en la tarjeta?",
      "step_dob": "¿Cuál es su fecha de nacimiento?",
      "step_country_code": "¿Cuál es el código de teléfono de su país?",
      "step_phone": "¿Cuál es su número de teléfono?",
      "step_address": "¿Cuál es su dirección?",
      "step_city": "¿En qué ciudad vive?",
      "step_state": "¿En qué estado/provincia vive?",
      "step_country": "¿En qué país vive?",
      "step_postal": "¿Cuál es su código postal?",
      "thank_you_apply": "Gracias, voy a solicitar la tarjeta para usted ahora.",
      "invalid_phone": "Entrada no válida. El número de teléfono no debe incluir espacios ni caracteres especiales. Inténtelo de nuevo.",
      "confirm": "Confirmar",
      "cancel": "Cancelar",
      "apply": "Solicitar",
      "done": "Hecho",
      "search_country": "Buscar País",
      "search_country_code": "Buscar Código de País",
      "select_dob": "Seleccionar Fecha de Nacimiento",
      "welcome_registered": "¡Bienvenido! ¿Ya estás registrado?",
      "great_email": "¡Genial! Ingrese su correo electrónico.",
      "now_password": "Ahora, ingrese su contraseña.",
      "invalid_password_format": "La contraseña debe tener 6 caracteres alfanuméricos. Inténtelo de nuevo.",
      "login_failed": "Error al iniciar sesión",
      "enter_email": "Ingrese correo...",
      "enter_password": "Ingrese contraseña...",
      "reset_link_sent": "Se ha enviado un enlace de restablecimiento si el correo está registrado.",
      "enter_email_first": "Por favor, ingrese primero su correo en el chat.",
      "forgot_password": "¿Olvidó su contraseña?",
      "yes": "Sí",
      "no": "No",
      "create_account": "Crear Cuenta",
      "let_create_account": "¡Vamos a crear tu cuenta! Ingrese su correo electrónico.",
      "choose_password": "¡Genial! Ahora elija una contraseña (6 caracteres alfanuméricos).",
      "registration_failed": "Error al registrarse",
      "card_details": "Detalles de la Tarjeta",
      "cardholder": "Titular",
      "expiry": "Expira",
      "billing_address": "Dirección de Facturación",
      "crypto_deposit": "Depósito Cripto",
      "today": "Hoy",
      "yesterday": "Ayer",
      "approval_failed": "Error en la aprobación. Inténtelo de nuevo.",
      "register_or_forgot": "¿Registrarse o Olvidó su contraseña?",
      "virtual_card_for": "Tarjeta virtual para",
      "splash_msg_1": "Emisión de tarjetas virtuales en su mejor expresión",
      "splash_msg_2": "Estamos disponibles en más de 100 países",
      "splash_msg_3": "Añadir a carteras Google Pay y Apple Pay (Próximamente)",
      "type_answer": "Escriba su respuesta...",
      "virtual_mastercards": "MasterCards Virtuales"
    },
    "th": {
      "app_name": "WalletCards",
      "my_cards": "บัตรของฉัน",
      "apply_new": "สมัครบัตรใหม่",
      "logout": "ออกจากระบบ",
      "settings": "การตั้งค่า",
      "language": "ภาษา",
      "select_language": "เลือกภาษา",
      "action_required": "ต้องดำเนินการ",
      "awaiting_payment": "รอการชำระเงิน",
      "pay_now": "ชำระเงินตอนนี้",
      "apply_for_card": "สมัครบัตรใบใหม่",
      "back": "กลับ",
      "current_balance": "ยอดเงินปัจจุบัน",
      "transactions": "รายการเดินบัญชี",
      "deposits": "รายการฝาก",
      "deposit_crypto": "ฝากคริปโต",
      "address_copied": "คัดลอกที่อยู่แล้ว",
      "card_payment": "การชำระเงินผ่านบัตร",
      "total_to_pay": "ยอดเงินทั้งหมดที่ต้องชำระ",
      "deposit_address": "ที่อยู่สำหรับฝากเงิน",
      "i_have_paid": "ฉันชำระเงินแล้ว",
      "login": "เข้าสู่ระบบ",
      "register": "ลงทะเบียน",
      "email": "อีเมล",
      "password": "รหัสผ่าน",
      "dont_have_account": "ยังไม่มีบัญชี? ลงทะเบียน",
      "already_have_account": "มีบัญชีอยู่แล้ว? เข้าสู่ระบบ",
      "user_not_found": "ไม่พบผู้ใช้",
      "3ds_auth": "การยืนยันตัวตน 3DS",
      "merchant": "ร้านค้า",
      "amount": "จำนวนเงิน",
      "approve": "อนุมัติ",
      "reject": "ปฏิเสธ",
      "approved": "อนุมัติแล้ว",
      "verify_details": "โปรดตรวจสอบรายละเอียดรายการก่อนอนุมัติ",
      "disclaimer_non_usdc": "สำหรับเหรียญที่ไม่ใช่ USDC จะมีค่าธรรมเนียมการฝาก 2% บวกค่าธรรมเนียมเครือข่าย อัตราแลกเปลี่ยนเป็น USDC ตามจริง",
      "disclaimer_exact_amount": "โปรดชำระตามยอดที่ระบุเท่านั้น ยอดที่น้อยกว่าอาจทำให้เงินสูญหาย ยอดเงิน 5.00\$ จะเป็นยอดเริ่มต้นในบัตร",
      "step_fee": "มีค่าธรรมเนียมสมัครบัตรใหม่ %s\$ โดย 5\$ จะเป็นยอดเงินคงเหลือในบัตร ยืนยันเพื่อดำเนินการต่อ",
      "step_first_name": "ชื่อจริงบนหน้าบัตรคืออะไร?",
      "step_last_name": "นามสกุลบนหน้าบัตรคืออะไร?",
      "step_dob": "วันเกิดของคุณคือวันที่เท่าไหร่?",
      "step_country_code": "รหัสโทรศัพท์ประเทศของคุณคืออะไร?",
      "step_phone": "เบอร์โทรศัพท์ของคุณคือเบอร์อะไร?",
      "step_address": "ที่อยู่ของคุณคือที่ไหน?",
      "step_city": "คุณอยู่อำเภอ/เขต อะไร?",
      "step_state": "คุณอยู่จังหวัดอะไร?",
      "step_country": "คุณอยู่ประเทศอะไร?",
      "step_postal": "รหัสไปรษณีย์ของคุณคืออะไร?",
      "thank_you_apply": "ขอบคุณ ฉันกำลังดำเนินการสมัครบัตรให้คุณ",
      "invalid_phone": "ข้อมูลไม่ถูกต้อง เบอร์โทรศัพท์ไม่ควรมีช่องว่างหรือตัวอักษรพิเศษ โปรดระบุใหม่อีกครั้ง",
      "confirm": "ยืนยัน",
      "cancel": "ยกเลิก",
      "apply": "สมัคร",
      "done": "เสร็จสิ้น",
      "search_country": "ค้นหาประเทศ",
      "search_country_code": "ค้นหารหัสประเทศ",
      "select_dob": "เลือกวันเกิด",
      "welcome_registered": "ยินดีต้อนรับ! คุณลงทะเบียนแล้วหรือยัง?",
      "great_email": "ยอดเยี่ยม! โปรดระบุอีเมลของคุณ",
      "now_password": "ตอนนี้ โปรดระบุรหัสผ่านของคุณ",
      "invalid_password_format": "รหัสผ่านต้องมี 6 หลัก เป็นตัวอักษรหรือตัวเลข โปรดลองอีกครั้ง",
      "login_failed": "เข้าสู่ระบบไม่สำเร็จ",
      "enter_email": "ระบุอีเมล...",
      "enter_password": "ระบุรหัสผ่าน...",
      "reset_link_sent": "หากอีเมลนี้ลงทะเบียนไว้ ลิงก์รีเซ็ตรหัสผ่านจะถูกส่งไป",
      "enter_email_first": "โปรดระบุอีเมลของคุณในแชทก่อน",
      "forgot_password": "ลืมรหัสผ่าน?",
      "yes": "ใช่",
      "no": "ไม่",
      "create_account": "สร้างบัญชี",
      "let_create_account": "มาสร้างบัญชีกันเถอะ! โปรดระบุอีเมลของคุณ",
      "choose_password": "ยอดเยี่ยม! ตอนนี้เลือกรหัสผ่าน (6 หลัก ตัวอักษรหรือตัวเลข)",
      "registration_failed": "ลงทะเบียนไม่สำเร็จ",
      "card_details": "รายละเอียดบัตร",
      "cardholder": "ชื่อผู้ถือบัตร",
      "expiry": "วันหมดอายุ",
      "billing_address": "ที่อยู่เรียกเก็บเงิน",
      "crypto_deposit": "ฝากคริปโต",
      "today": "วันนี้",
      "yesterday": "เมื่อวาน",
      "approval_failed": "การอนุมัติล้มเหลว โปรดลองอีกครั้ง",
      "register_or_forgot": "ลงทะเบียน หรือ ลืมรหัสผ่าน?",
      "virtual_card_for": "บัตรเสมือนสำหรับ",
      "splash_msg_1": "การออกบัตรเสมือนจริงที่ดีที่สุด",
      "splash_msg_2": "เรามีให้บริการในกว่า 100 ประเทศ",
      "splash_msg_3": "เพิ่มในกระเป๋าเงิน Google Pay และ Apple Pay (เร็วๆ นี้)",
      "type_answer": "พิมพ์คำตอบของคุณ...",
      "virtual_mastercards": "Virtual MasterCards"
    },
    "pt": {
      "app_name": "WalletCards",
      "my_cards": "Meus Cartões",
      "apply_new": "Solicitar Novo",
      "logout": "Sair",
      "settings": "Configurações",
      "language": "Idioma",
      "select_language": "Selecionar Idioma",
      "action_required": "Ação Necessária",
      "awaiting_payment": "Aguardando Pagamento",
      "pay_now": "Pagar Agora",
      "apply_for_card": "Solicitar Novo Cartão",
      "back": "Voltar",
      "current_balance": "Saldo Atual",
      "transactions": "Transactions",
      "deposits": "Depósitos",
      "deposit_crypto": "Depositar Cripto",
      "address_copied": "Endereço copiado",
      "card_payment": "Pagamento com Cartão",
      "total_to_pay": "Valor Total a Pagar",
      "deposit_address": "Endereço de Depósito",
      "i_have_paid": "Já Paguei",
      "login": "Entrar",
      "register": "Registrar",
      "email": "E-mail",
      "password": "Senha",
      "dont_have_account": "Não tem conta? Registre-se",
      "already_have_account": "Já tem conta? Entre",
      "user_not_found": "Usuário Não Encontrado",
      "3ds_auth": "Autenticação 3DS",
      "merchant": "Estabelecimento",
      "amount": "Valor",
      "approve": "Aprovar",
      "reject": "Rejeitar",
      "approved": "Aprovado",
      "verify_details": "Verifique os detalhes da transação antes de aprovar.",
      "disclaimer_non_usdc": "Para moedas não-USDC, aplicam-se taxas de depósito de 2% mais taxas de rede. Taxas de câmbio para USDC conforme o valor real.",
      "disclaimer_exact_amount": "Pague apenas o valor exato. Valores menores podem resultar em perda de fundos. \$5.00 permanecerão como saldo inicial.",
      "step_fee": "Há uma taxa de \$%s para novos cartões, dos quais \$5 permanecerão como saldo. Confirme para continuar.",
      "step_first_name": "Qual será o primeiro nome no cartão?",
      "step_last_name": "Qual será o sobrenome no cartão?",
      "step_dob": "Qual é a sua data de nascimento?",
      "step_country_code": "Qual é o código de telefone do seu país?",
      "step_phone": "Qual é o seu número de telefone?",
      "step_address": "Qual é o seu endereço?",
      "step_city": "Qual é a sua cidade?",
      "step_state": "Qual é o seu estado/província?",
      "step_country": "Qual é o seu país?",
      "step_postal": "Qual é o seu código postal?",
      "thank_you_apply": "Obrigado, vou solicitar o cartão para você agora.",
      "invalid_phone": "Entrada inválida. O número de telefone não deve incluir espaços ou caracteres especiais. Tente novamente.",
      "confirm": "Confirmar",
      "cancel": "Cancelar",
      "apply": "Solicitar",
      "done": "Concluído",
      "search_country": "Buscar País",
      "search_country_code": "Buscar Código",
      "select_dob": "Selecionar Data de Nascimento",
      "welcome_registered": "Bem-vindo! Você já é registrado?",
      "great_email": "Ótimo! Digite seu e-mail.",
      "now_password": "Agora, digite sua senha.",
      "invalid_password_format": "A senha deve ter 6 caracteres alfanuméricos. Tente novamente.",
      "login_failed": "Falha ao entrar",
      "enter_email": "Digite o e-mail...",
      "enter_password": "Digite a senha...",
      "reset_link_sent": "Um link de redefinição foi enviado se o e-mail estiver registrado.",
      "enter_email_first": "Digite seu e-mail no chat primeiro.",
      "forgot_password": "Esqueceu a senha?",
      "yes": "Sí",
      "no": "Não",
      "create_account": "Criar Conta",
      "let_create_account": "Vamos criar sua conta! Digite seu e-mail.",
      "choose_password": "Ótimo! Agora escolha uma senha (6 caracteres alfanuméricos).",
      "registration_failed": "Falha ao registrar",
      "card_details": "Detalhes do Cartão",
      "cardholder": "Titular",
      "expiry": "Validade",
      "billing_address": "Endereço de Cobrança",
      "crypto_deposit": "Depósito Cripto",
      "today": "Hoje",
      "yesterday": "Ontem",
      "approval_failed": "Falha na aprovação. Tente novamente.",
      "register_or_forgot": "Registrar ou Esqueceu a senha?",
      "virtual_card_for": "Cartão virtual para",
      "splash_msg_1": "Emissão de cartões virtuais no seu melhor",
      "splash_msg_2": "Estamos disponíveis em mais de 100 países",
      "splash_msg_3": "Adicionar às carteiras Google Pay e Apple Pay (Em breve)",
      "type_answer": "Digite sua resposta...",
      "virtual_mastercards": "MasterCards Virtuais"
    },
    "ht": {
      "app_name": "WalletCards",
      "my_cards": "Kat Mwen Yo",
      "apply_new": "Aplike pou nèf",
      "logout": "Dekonekte",
      "settings": "Anviwònman",
      "language": "Lang",
      "select_language": "Chwazi Lang",
      "action_required": "Aksyon Obligatwa",
      "awaiting_payment": "Ap Tann Peman",
      "pay_now": "Peye Kounye a",
      "apply_for_card": "Mande yon Nouvo Kat",
      "back": "Retounen",
      "current_balance": "Balans Kounye a",
      "transactions": "Tranzaksyon",
      "deposits": "Depo",
      "deposit_crypto": "Depoze Kripto",
      "address_copied": "Adrès kopye",
      "card_payment": "Peman ak Kat",
      "total_to_pay": "Kantite Total pou Peye",
      "deposit_address": "Adrès Depo",
      "i_have_paid": "Mwen te Peye",
      "login": "Konekte",
      "register": "Enskri",
      "email": "Imèl",
      "password": "Modpas",
      "dont_have_account": "Ou pa gen kont? Enskri",
      "already_have_account": "Ou gen kont deja? Konekte",
      "user_not_found": "Itilizatè pa jwenn",
      "3ds_auth": "Otantifikasyon 3DS",
      "merchant": "Komèsan",
      "amount": "Kantite",
      "approve": "Apwouve",
      "reject": "Rejte",
      "approved": "Apwouve deja",
      "verify_details": "Tanpri verifye detay tranzaksyon an anvan ou apwouve.",
      "disclaimer_non_usdc": "Pour pyès ki pa USDC, gen frè depo 2% plis frè rezo. To echanj USDC se sa ki reyèl la.",
      "disclaimer_exact_amount": "Tanpri peye kantite egzak la sèlman. Mwens kantite ka fè w pèdi lajan an. \$5.00 ap rete kòm balans ou.",
      "step_fee": "Gen yon frè \$%s pou nouvo kat, nan sa \$5 ap rete kòm balans ou. Konfime pou kontinye.",
      "step_first_name": "Ki premye non ki pral sou kat la?",
      "step_last_name": "Ki dènye non ki pral sou kat la?",
      "step_dob": "Ki dat ou te fèt?",
      "step_country_code": "Ki kòd telefòn peyi w?",
      "step_phone": "Ki nimewo telefòn ou?",
      "step_address": "Ki adrès ou?",
      "step_city": "Nan ki vil ou rete?",
      "step_state": "Nan ki leta/pwovens ou rete?",
      "step_country": "Nan ki peyi ou rete?",
      "step_postal": "Ki kòd postal ou?",
      "thank_you_apply": "Mèsi, mwen pral mande kat la pou ou kounye a.",
      "invalid_phone": "Enfòmasyon pa bon. Nimewo telefòn lan pa dwe gen espas oswa karaktè espesyal. Refè l ankò.",
      "confirm": "Konfime",
      "cancel": "Anile",
      "apply": "Aplike",
      "done": "Fini",
      "search_country": "Chèche Peyi",
      "search_country_code": "Chèche Kòd Peyi",
      "select_dob": "Chwazi Dat Nesans",
      "welcome_registered": "Byenveni! Èske w enskri deja?",
      "great_email": "Trè byen! Tanpri antre imèl ou.",
      "now_password": "Kounye a, tanpri antre modpas ou.",
      "invalid_password_format": "Modpas la dwe gen 6 karaktè (lèt ak nimewo). Tanpri reseye.",
      "login_failed": "Koneksyon an echwe",
      "enter_email": "Antre imèl...",
      "enter_password": "Antre modpas...",
      "reset_link_sent": "Yon lyen pou chanje modpas voye si imèl sa enskri.",
      "enter_email_first": "Tanpri antre imèl ou nan chat la anvan.",
      "forgot_password": "Bliye modpas?",
      "yes": "Wi",
      "no": "Non",
      "create_account": "Kreye yon Kont",
      "let_create_account": "Ann kreye kont ou! Tanpri antre imèl ou.",
      "choose_password": "Trè byen! Kounye a chwazi yon modpas (6 karaktè lèt ak nimewo).",
      "registration_failed": "Enskripsyon an echwe",
      "card_details": "Detay Kat la",
      "cardholder": "Mèt Kat la",
      "expiry": "Ekspirasyon",
      "billing_address": "Adrès Faktirasyon",
      "crypto_deposit": "Depo Kripto",
      "today": "Jodi a",
      "yesterday": "Yè",
      "approval_failed": "Apwobasyon an echwe. Tanpri reseye.",
      "register_or_forgot": "Enskri oswa Bliye modpas?",
      "virtual_card_for": "Kat vityèl pou",
      "splash_msg_1": "Emisyon kat vityèl nan pi bon li yo",
      "splash_msg_2": "Nou disponib nan plis pase 100 peyi",
      "splash_msg_3": "Ajoute nan bous Google Pay ak Apple Pay (Ap vini talè)",
      "type_answer": "Tape repons ou...",
      "virtual_mastercards": "Virtual MasterCards"
    },
    "nl": {
      "app_name": "WalletCards",
      "my_cards": "Mijn Kaarten",
      "apply_new": "Nieuwe Aanvragen",
      "logout": "Uitloggen",
      "settings": "Instellingen",
      "language": "Taal",
      "select_language": "Selecteer Taal",
      "action_required": "Actie Vereist",
      "awaiting_payment": "Wachten op Betaling",
      "pay_now": "Nu Betalen",
      "apply_for_card": "Nieuwe Kaart Aanvragen",
      "back": "Terug",
      "current_balance": "Huidig Saldo",
      "transactions": "Transacties",
      "deposits": "Stortingen",
      "deposit_crypto": "Crypto Storten",
      "address_copied": "Adres gekopieerd",
      "card_payment": "Kaartbetaling",
      "total_to_pay": "Totaal te Betalen",
      "deposit_address": "Stortingsadres",
      "i_have_paid": "Ik Heb Betaald",
      "login": "Inloggen",
      "register": "Registreren",
      "email": "E-mail",
      "password": "Wachtwoord",
      "dont_have_account": "Geen account? Registreer",
      "already_have_account": "Al een account? Log in",
      "user_not_found": "Gebruiker Niet Gevonden",
      "3ds_auth": "3DS Authenticatie",
      "merchant": "Winkelier",
      "amount": "Bedrag",
      "approve": "Goedkeuren",
      "reject": "Afwijzen",
      "approved": "Goedgekeurd",
      "verify_details": "Controleer de transactiegegevens voordat u goedkeurt.",
      "disclaimer_non_usdc": "Voor niet-USDC-munten geldt 2% stortingskosten plus netwerkkosten. Wisselkoersen naar USDC zijn actueel.",
      "disclaimer_exact_amount": "Betaal alleen het exacte bedrag. Lagere bedragen kunnen leiden tot verlies van geld. \$5.00 blijft over als beginsaldo.",
      "step_fee": "Er is een vergoeding van \$%s voor nieuwe kaarten, waarvan \$5 als saldo overblijft. Bevestig om door te gaan.",
      "step_first_name": "Wat is de voornaam op de kaart?",
      "step_last_name": "Wat is de achternaam op de kaart?",
      "step_dob": "Wat is uw geboortedatum?",
      "step_country_code": "Wat is de landcode van uw telefoon?",
      "step_phone": "Wat is uw telefoonnummer?",
      "step_address": "Wat is uw adres?",
      "step_city": "In welke stad woont u?",
      "step_state": "In welke provincie woont u?",
      "step_country": "In welk land woont u?",
      "step_postal": "Wat is uw postcode?",
      "thank_you_apply": "Bedankt, ik ga de kaart nu voor u aanvragen.",
      "invalid_phone": "Ongeldige invoer. Het telefoonnummer mag geen spaties of speciale tekens bevatten. Probeer het opnieuw.",
      "confirm": "Bevestigen",
      "cancel": "Annuleren",
      "apply": "Aanvragen",
      "done": "Klaar",
      "search_country": "Land Zoeken",
      "search_country_code": "Landcode Zoeken",
      "select_dob": "Selecteer Geboortedatum",
      "welcome_registered": "Welkom! Bent u al geregistreerd?",
      "great_email": "Geweldig! Voer uw e-mailadres in.",
      "now_password": "Voer nu uw wachtwoord in.",
      "invalid_password_format": "Wachtwoord moet 6 alfanumerieke tekens zijn. Probeer het opnieuw.",
      "login_failed": "Inloggen mislukt",
      "enter_email": "Voer e-mail in...",
      "enter_password": "Voer wachtwoord in...",
      "reset_link_sent": "Een herstellink is verzonden als het e-mailadres bekend is.",
      "enter_email_first": "Voer eerst uw e-mailadres in de chat in.",
      "forgot_password": "Wachtwoord vergeten?",
      "yes": "Ja",
      "no": "Nee",
      "create_account": "Account Aanmaken",
      "let_create_account": "Laten we uw account aanmaken! Voer uw e-mailadres in.",
      "choose_password": "Geweldig! Kies nu een wachtwoord (6 alfanumerieke tekens).",
      "registration_failed": "Registratie mislukt",
      "card_details": "Kaartgegevens",
      "cardholder": "Kaarthouder",
      "expiry": "Vervaldatum",
      "billing_address": "Factuuradres",
      "crypto_deposit": "Crypto Storting",
      "today": "Vandaag",
      "yesterday": "Gisteren",
      "approval_failed": "Goedkeuring mislukt. Probeer het opnieuw.",
      "register_or_forgot": "Registreren of Wachtwoord vergeten?",
      "virtual_card_for": "Virtuele kaart voor",
      "splash_msg_1": "Uitgifte van virtuele kaarten op zijn best",
      "splash_msg_2": "We zijn beschikbaar in meer dan 100 landen",
      "splash_msg_3": "Toevoegen aan portefeuilles Google Pay en Apple Pay (Binnenkort beschikbaar)",
      "type_answer": "Typ je antwoord...",
      "virtual_mastercards": "Virtuele MasterCards"
    },
    "he": {
      "app_name": "WalletCards",
      "my_cards": "הכרטיסים שלי",
      "apply_new": "הזמנת חדש",
      "logout": "התנתקות",
      "settings": "הגדרות",
      "language": "שפה",
      "select_language": "בחירת שפה",
      "action_required": "נדרשת פעולה",
      "awaiting_payment": "ממתין לתשלום",
      "pay_now": "שלם עכשיו",
      "apply_for_card": "בקשת כרטיס חדש",
      "back": "חזור",
      "current_balance": "יתרה נוכחית",
      "transactions": "עסקאות",
      "deposits": "הפקדות",
      "deposit_crypto": "הפקדת קריפטו",
      "address_copied": "הכתובת הועתקה",
      "card_payment": "תשלום בכרטיס",
      "total_to_pay": "סה\"כ לתשלום",
      "deposit_address": "כתובת להפקדה",
      "i_have_paid": "שילמתי",
      "login": "התחברות",
      "register": "הרשמה",
      "email": "אימייל",
      "password": "סיסמה",
      "dont_have_account": "אין לך חשבון? הירשם",
      "already_have_account": "כבר יש לך חשבון? התחבר",
      "user_not_found": "משתמש לא נמצא",
      "3ds_auth": "אימות 3DS",
      "merchant": "בית עסק",
      "amount": "סכום",
      "approve": "אשר",
      "reject": "דחה",
      "approved": "אושר",
      "verify_details": "אנא ודא את פרטי העסקה לפני האישור.",
      "disclaimer_non_usdc": "עבור מטבעות שאינם USDC, חלה עמלת הפקדה של 2% בתוספת עמלות רשת. שערי החליפין ל-USDC הם לפי הערך בפועל.",
      "disclaimer_exact_amount": "אנא שלם את הסכום המדויק בלבד. סכומים נמוכים יותר עלולים לגרום לאובדן הכספים. \$5.00 יישארו כיתרה ראשונית.",
      "step_fee": "ישנה עמלה עבור כרטיסים חדשים בסך \$%s מתוכם \$5 יישארו כיתרה שלך. אשר להמשך.",
      "step_first_name": "מה יהיה השם הפרטי על הכרטיס?",
      "step_last_name": "מה יהיה שם המשפחה על הכרטיס?",
      "step_dob": "מהו תאריך הלידה שלך?",
      "step_country_code": "מהו קידומת הטלפון של המדינה שלך?",
      "step_phone": "מהו מספר הטלפון שלך?",
      "step_address": "מהי הכתובת שלך?",
      "step_city": "באיזו עיר אתה גר?",
      "step_state": "באיזה מחוז/מדינה אתה גר?",
      "step_country": "באיזו מדינה אתה גר?",
      "step_postal": "מהו המיקוד שלך?",
      "thank_you_apply": "תודה, אני הולך לבקש את הכרטיס עבורך עכשיו.",
      "invalid_phone": "קלט לא תקין. מספר הטלפון לא צריך לכלול רווחים או תווים מיוחדים. אנא נסה שוב.",
      "confirm": "אישור",
      "cancel": "ביטול",
      "apply": "הגש בקשה",
      "done": "בוצע",
      "search_country": "חיפוש מדינה",
      "search_country_code": "חיפוש קידומת",
      "select_dob": "בחר תאריך לידה",
      "welcome_registered": "ברוך הבא! האם אתה כבר רשום?",
      "great_email": "נהדר! אנא הזן את כתובת האימייל שלך.",
      "now_password": "עכשיו, אנא הזן את הסיסמה שלך.",
      "invalid_password_format": "הסיסמה חייבת לכלול 6 תווים אלפאנומריים. אנא נסה שוב.",
      "login_failed": "התחברות נכשלה",
      "enter_email": "הזן אימייל...",
      "enter_password": "הזן סיסמה...",
      "reset_link_sent": "קישור לאיפוס נשלח אם האימייל רשום.",
      "enter_email_first": "אנא הזן תחילה את האימייל שלך בצ'אט.",
      "forgot_password": "שכחת סיסמה?",
      "yes": "כן",
      "no": "לא",
      "create_account": "יצירת חשבון",
      "let_create_account": "בוא ניצור את החשבון שלך! אנא הזן את כתובת האימייל שלך.",
      "choose_password": "נהדר! עכשיו בחר סיסמה (6 תווים אלפאנומריים).",
      "registration_failed": "הרשמה נכשלה",
      "card_details": "פרטי כרטיס",
      "cardholder": "בעל הכרטיס",
      "expiry": "תוקף",
      "billing_address": "כתובת לחיוב",
      "crypto_deposit": "הפקדת קריפטו",
      "today": "היום",
      "yesterday": "אתמול",
      "approval_failed": "האישור נכשל. אנא נסה שוב.",
      "register_or_forgot": "הרשמה או שכחת סיסמה?",
      "virtual_card_for": "כרטיס וירטואלי עבור",
      "splash_msg_1": "הנפקת כרטיס וירטואלי במיטבה",
      "splash_msg_2": "אנחנו זמינים ב-100+ מדינות",
      "splash_msg_3": "הוסף לארנקים Google Pay ו-Apple Pay (בקרוב)",
      "type_answer": "הקלד את תשובתך...",
      "virtual_mastercards": "MasterCards וירטואליים"
    },
    "ar": {
      "app_name": "WalletCards",
      "my_cards": "بطاقاتي",
      "apply_new": "طلب جديد",
      "logout": "تسجيل الخروج",
      "settings": "الإعدادات",
      "language": "اللغة",
      "select_language": "اختر اللغة",
      "action_required": "إجراء مطلوب",
      "awaiting_payment": "بانتظار الدفع",
      "pay_now": "ادفع الآن",
      "apply_for_card": "طلب بطاقة جديدة",
      "back": "رجوع",
      "current_balance": "الرصيد الحالي",
      "transactions": "المعاملات",
      "deposits": "الإيداعات",
      "deposit_crypto": "إيداع كريبتو",
      "address_copied": "تم نسخ العنوان",
      "card_payment": "الدفع بالبطاقة",
      "total_to_pay": "المبلغ الإجمالي للدفع",
      "deposit_address": "عنوان الإيداع",
      "i_have_paid": "لقد دفعت",
      "login": "تسجيل الدخول",
      "register": "تسجيل",
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "dont_have_account": "ليس لديك حساب؟ سجل الآن",
      "already_have_account": "لديك حساب بالفعل؟ سجل دخولك",
      "user_not_found": "المستخدم غير موجود",
      "3ds_auth": "مصادقة 3DS",
      "merchant": "التاجر",
      "amount": "المبلغ",
      "approve": "موافقة",
      "reject": "رفض",
      "approved": "تمت الموافقة",
      "verify_details": "يرجى التحقق من تفاصيل المعاملة قبل الموافقة.",
      "disclaimer_non_usdc": "بالنسبة للعملات بخلاف USDC، تطبق رسوم إيداع 2٪ بالإضافة إلى رسوم الشبكة. أسعار الصرف إلى USDC هي بالقيم الفعلية.",
      "disclaimer_exact_amount": "يرجى دفع المبلغ المحدد فقط. المبالغ الأقل قد تؤدي إلى فقدان الأموال. \$5.00 سيبقى كرصيد أولي للبطاقة.",
      "step_fee": "هناك رسوم للبطاقات الجديدة قدرها %s\$ سيبقى منها 5\$ كرصيد لك. أكد للمتابعة.",
      "step_first_name": "ما هو الاسم الأول الذي سيظهر على البطاقة؟",
      "step_last_name": "ما هو اسم العائلة الذي سيظهر على البطاقة؟",
      "step_dob": "ما هو تاريخ ميلادك؟",
      "step_country_code": "ما هو رمز الاتصال الدولي لبلدك؟",
      "step_phone": "ما هو رقم هاتفك؟",
      "step_address": "ما هو عنوانك؟",
      "step_city": "في أي مدينة تسكن؟",
      "step_state": "في أي ولاية/محافظة تسكن؟",
      "step_country": "في أي بلد تسكن؟",
      "step_postal": "ما هو الرمز البريدي؟",
      "thank_you_apply": "شكراً لك، سأقوم بطلب البطاقة لك الآن.",
      "invalid_phone": "إدخال غير صحيح. يجب ألا يتضمن رقم الهاتف أي مسافات أو رموز خاصة. يرجى المحاولة مرة أخرى.",
      "confirm": "تأكيد",
      "cancel": "إلغاء",
      "apply": "طلب",
      "done": "تم",
      "search_country": "بحث عن بلد",
      "search_country_code": "بحث عن رمز بلد",
      "select_dob": "اختر تاريخ الميلاد",
      "welcome_registered": "مرحباً! هل أنت مسجل بالفعل؟",
      "great_email": "رائع! يرجى إدخال بريدك الإلكتروني.",
      "now_password": "الآن، يرجى إدخال كلمة المرور الخاصة بك.",
      "invalid_password_format": "يجب أن تتكون كلمة المرور من 6 أحرف أو أرقام. يرجى المحاولة مرة أخرى.",
      "login_failed": "فشل تسجيل الدخول",
      "enter_email": "أدخل البريد الإلكتروني...",
      "enter_password": "أدخل كلمة المرور...",
      "reset_link_sent": "تم إرسال رابط إعادة التعيين إذا كان البريد مسجلاً.",
      "enter_email_first": "يرجى إدخال بريدك الإلكتروني في الدردشة أولاً.",
      "forgot_password": "نسيت كلمة المرور؟",
      "yes": "نعم",
      "no": "لا",
      "create_account": "إنشاء حساب",
      "let_create_account": "لنقم بإنشاء حسابك! يرجى إدخال بريدك الإلكتروني.",
      "choose_password": "رائع! الآن اختر كلمة مرور (6 أحرف أو أرقام).",
      "registration_failed": "فشل التسجيل",
      "card_details": "تفاصيل البطاقة",
      "cardholder": "حامل البطاقة",
      "expiry": "تاريخ الانتهاء",
      "billing_address": "عنوان الفواتير",
      "crypto_deposit": "إيداع كريبتو",
      "today": "اليوم",
      "yesterday": "أمس",
      "approval_failed": "فشل الموافقة. يرجى المحاولة مرة أخرى.",
      "register_or_forgot": "تسجيل أو نسيت كلمة المرور؟",
      "virtual_card_for": "بطاقة افتراضية لـ",
      "splash_msg_1": "إصدار البطاقة الافتراضية في أفضل حالاته",
      "splash_msg_2": "نحن متاحون في أكثر من 100 دولة",
      "splash_msg_3": "أضف إلى محافظ Google Pay و Apple Pay (قريبًا)",
      "type_answer": "اكتب إجابتك...",
      "virtual_mastercards": "ماستركارد افتراضية"
    }
  };

  String getString(String key) {
    return _translations[_selectedLanguage]?[key] ?? _translations["en"]?[key] ?? key;
  }
}
