package com.app.walletcards.util

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object LocalizationUtil {
    private const val PREFS_NAME = "wallet_prefs"
    private const val KEY_LANG = "selected_language"

    var selectedLanguage by mutableStateOf("en")

    fun loadLanguage(context: Context) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        selectedLanguage = prefs.getString(KEY_LANG, "") ?: ""
    }

    fun saveLanguage(context: Context, lang: String) {
        selectedLanguage = lang
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_LANG, lang).apply()
    }

    fun isLanguageSet(context: Context): Boolean {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        return prefs.getString(KEY_LANG, "")?.isNotEmpty() == true
    }

    val supportedLanguages = listOf(
        Triple("🇺🇸 English", "en", "English"),
        Triple("🇫🇷 Français", "fr", "French"),
        Triple("🇪🇸 Español", "es", "Spanish"),
        Triple("🇹🇭 ไทย", "th", "Thai"),
        Triple("🇵🇹 Português", "pt", "Portuguese"),
        Triple("🇭🇹 Kreyòl Ayisyen", "ht", "Haitian Creole"),
        Triple("🇳🇱 Nederlands", "nl", "Dutch"),
        Triple("🇮🇱 עברית", "he", "Hebrew"),
        Triple("🇸🇦 العربية", "ar", "Arabic")
    )

    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "My Cards",
            "apply_new" to "Apply New",
            "logout" to "Logout",
            "settings" to "Settings",
            "language" to "Language",
            "select_language" to "Select Language",
            "action_required" to "Action Required",
            "awaiting_payment" to "Awaiting Payment",
            "pay_now" to "Pay Now",
            "apply_for_card" to "Apply for New Card",
            "back" to "Back",
            "current_balance" to "Current Balance",
            "transactions" to "Transactions",
            "deposits" to "Deposits",
            "deposit_crypto" to "Deposit Crypto",
            "address_copied" to "Address copied",
            "card_payment" to "Card Payment",
            "total_to_pay" to "Total Amount to Pay",
            "deposit_address" to "Deposit Address",
            "i_have_paid" to "I Have Paid",
            "login" to "Login",
            "register" to "Register",
            "email" to "Email",
            "password" to "Password",
            "dont_have_account" to "Don't have an account? Register",
            "already_have_account" to "Already have an account? Login",
            "user_not_found" to "User Not Found",
            "3ds_auth" to "3DS Authentication",
            "merchant" to "Merchant",
            "amount" to "Amount",
            "approve" to "Approve",
            "reject" to "Reject",
            "approved" to "Approved",
            "verify_details" to "Please verify the transaction details before approving.",
            "disclaimer_non_usdc" to "For non USDC coins deposit fees 2% plus network fees apply. Coins to USDC exchange rates at actual's.",
            "disclaimer_exact_amount" to "Kindly pay the exact amount only. Lower amounts may cause loss of funds. $5.00 will remain as your initial card balance.",
            "step_fee" to "There is a fee for new cards of $%s out of which $5 will remain as your card balance. Confirm to continue.",
            "step_first_name" to "What will be the first name on the card?",
            "step_last_name" to "What will be the last name on the card?",
            "step_dob" to "What is your date of birth?",
            "step_country_code" to "What is your country phonecode?",
            "step_phone" to "What is your phone number?",
            "step_address" to "What is your address?",
            "step_city" to "What is your city?",
            "step_state" to "What is your state?",
            "step_country" to "What is your country?",
            "step_postal" to "What is your postal code?",
            "thank_you_apply" to "Thank you, I am going to apply the card for you now.",
            "invalid_phone" to "Invalid input. The phone number should not include any spaces or special characters. Please re-enter your phone number.",
            "confirm" to "Confirm",
            "cancel" to "Cancel",
            "apply" to "Apply",
            "done" to "Done",
            "search_country" to "Search Country",
            "search_country_code" to "Search Country Code",
            "select_dob" to "Select Date of Birth",
            "welcome_registered" to "Welcome! Are you already registered?",
            "great_email" to "Great! Please enter your email address.",
            "now_password" to "Now, please enter your password.",
            "invalid_password_format" to "Password must be 6 alphanumeric characters. Please try again.",
            "login_failed" to "Login failed",
            "enter_email" to "Enter email...",
            "enter_password" to "Enter password...",
            "reset_link_sent" to "If this email is registered, a password reset link has been sent.",
            "enter_email_first" to "Please enter your email address in the chat first.",
            "forgot_password" to "Forgot Password?",
            "yes" to "Yes",
            "no" to "No",
            "create_account" to "Create Account",
            "let_create_account" to "Let's create your account! Please enter your email address.",
            "choose_password" to "Great! Now, please choose a password (6 alphanumeric characters).",
            "registration_failed" to "Registration failed",
            "card_details" to "Card Details",
            "cardholder" to "Cardholder",
            "addon_cardholder" to "Addon Cardholder",
            "expiry" to "Expiry",
            "billing_address" to "Billing Address",
            "crypto_deposit" to "Crypto Deposit",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "approval_failed" to "Approval failed. Please try again.",
            "register_or_forgot" to "Register or Forgot Password?",
            "virtual_card_for" to "Virtual Card for %s",
            "virtual_card" to "Virtual Card",
            "share_app" to "Share App",
            "review_app" to "Review App",
            "delete_account" to "Delete Account",
            "delete_disclaimer" to "Your account will be deleted immediately, your card transaction details will be kept on record for 2 years as required by governing AML policies.",
            "are_you_sure" to "Are you sure?",
            "share_text" to "Check out WalletCards! The best virtual mastercards for crypto offramp. Download now!",
            "apply_addon" to "Apply Addon",
            "apply_for_addon" to "Apply for Addon Card",
            "addon_info" to "Addon cards use the same balance as the primary card. The fee for the add on card will be deducted from the primary card balance.",
            "insufficient_balance" to "Not sufficient balance",
            "addon_issued" to "Add on card issued",
            "continue" to "Continue",
            "addon_cards" to "Addon Cards",
            "no_addon_cards" to "No add on cards",
            "addon_card_badge" to "ADDON CARD"
        ),
        "fr" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "Mes Cartes",
            "apply_new" to "Nouvelle Carte",
            "logout" to "Déconnexion",
            "settings" to "Paramètres",
            "language" to "Langue",
            "select_language" to "Choisir la Langue",
            "action_required" to "Action Requise",
            "awaiting_payment" to "En Attente de Paiement",
            "pay_now" to "Payer Maintenant",
            "apply_for_card" to "Demander une Nouvelle Carte",
            "back" to "Retour",
            "current_balance" to "Solde Actuel",
            "transactions" to "Transactions",
            "deposits" to "Dépôts",
            "deposit_crypto" to "Déposer de la Crypto",
            "address_copied" to "Adresse copiée",
            "card_payment" to "Paiement par Carte",
            "total_to_pay" to "Montant Total à Payer",
            "deposit_address" to "Adresse de Dépôt",
            "i_have_paid" to "J'ai Payé",
            "login" to "Connexion",
            "register" to "S'inscrire",
            "email" to "Email",
            "password" to "Mot de Passe",
            "dont_have_account" to "Pas de compte ? S'inscrire",
            "already_have_account" to "Déjà un compte ? Connexion",
            "user_not_found" to "Utilisateur Non Trouvé",
            "3ds_auth" to "Authentification 3DS",
            "merchant" to "Marchand",
            "amount" to "Montant",
            "approve" to "Approuver",
            "reject" to "Rejeter",
            "approved" to "Approuvé",
            "verify_details" to "Veuillez vérifier les détails de la transaction avant d'approuver.",
            "disclaimer_non_usdc" to "Pour les pièces non USDC, des frais de dépôt de 2% plus les frais de réseau s'appliquent. Taux de change des pièces en USDC au réel.",
            "disclaimer_exact_amount" to "Veuillez payer exactement le montant indiqué. Des montants inférieurs peuvent entraîner une perte de fonds. 5,00 $ resteront comme solde initial de votre carte.",
            "step_fee" to "Il y a des frais pour les nouvelles cartes de %s $ dont 5 $ resteront comme solde de votre carte. Confirmez pour continuer.",
            "step_first_name" to "Quel sera le prénom sur la carte ?",
            "step_last_name" to "Quel sera le nom de famille sur la carte ?",
            "step_dob" to "Quelle est votre date de naissance ?",
            "step_country_code" to "Quel est l'indicatif téléphonique de votre pays ?",
            "step_phone" to "Quel est votre numéro de téléphone ?",
            "step_address" to "Quelle est votre adresse ?",
            "step_city" to "Quelle est votre ville ?",
            "step_state" to "Quel est votre état/province ?",
            "step_country" to "Quel est votre pays ?",
            "step_postal" to "Quel est votre code postal ?",
            "thank_you_apply" to "Merci, je vais maintenant demander la carte pour vous.",
            "invalid_phone" to "Entrée non valide. Le numéro de téléphone ne doit pas inclure d'espaces ou de caractères spéciaux. Veuillez saisir à nouveau votre numéro de téléphone.",
            "confirm" to "Confirmer",
            "cancel" to "Annuler",
            "apply" to "Appliquer",
            "done" to "Terminé",
            "search_country" to "Rechercher un Pays",
            "search_country_code" to "Rechercher un Indicatif",
            "select_dob" to "Sélectionner la Date de Naissance",
            "welcome_registered" to "Bienvenue ! Êtes-vous déjà inscrit ?",
            "great_email" to "Génial ! Veuillez entrer votre adresse e-mail.",
            "now_password" to "Maintenant, veuillez entrer votre mot de passe.",
            "invalid_password_format" to "Le mot de passe doit comporter 6 caractères alphanumériques. Veuillez réessayer.",
            "login_failed" to "Échec de la connexion",
            "enter_email" to "Entrer l'e-mail...",
            "enter_password" to "Entrer le mot de passe...",
            "reset_link_sent" to "Si cet e-mail est enregistré, un lien de réinitialisation de mot de passe a été envoyé.",
            "enter_email_first" to "Veuillez d'abord entrer votre adresse e-mail dans le chat.",
            "forgot_password" to "Mot de passe oublié ?",
            "yes" to "Oui",
            "no" to "Non",
            "create_account" to "Créer un compte",
            "let_create_account" to "Créons votre compte ! Veuillez entrer votre adresse e-mail.",
            "choose_password" to "Génial ! Maintenant, veuillez choisir un mot de passe (6 caractères alphanumériques).",
            "registration_failed" to "Échec de l'enregistrement",
            "card_details" to "Détails de la carte",
            "cardholder" to "Titulaire",
            "addon_cardholder" to "Titulaire supplémentaire",
            "expiry" to "Expire le",
            "billing_address" to "Adresse de facturation",
            "crypto_deposit" to "Dépôt de Crypto",
            "today" to "Aujourd'hui",
            "yesterday" to "Hier",
            "approval_failed" to "Échec de l'approbation. Veuillez réessayer.",
            "register_or_forgot" to "S'inscrire ou Mot de passe oublié ?",
            "virtual_card_for" to "Carte virtuelle pour %s",
            "virtual_card" to "Carte virtuelle",
            "share_app" to "Partager l'application",
            "review_app" to "Évaluer l'application",
            "delete_account" to "Supprimer le compte",
            "delete_disclaimer" to "Votre compte sera supprimé immédiatement, les détails des transactions de votre carte seront conservés pendant 2 ans comme requis par les politiques de lutte contre le blanchiment d'argent.",
            "are_you_sure" to "Êtes-vous sûr ?",
            "apply_addon" to "Appliquer l'addon",
            "apply_for_addon" to "Demander une carte supplémentaire",
            "addon_info" to "Les cartes supplémentaires utilisent le même solde que la carte principale. Les frais pour la carte supplémentaire seront déduits du solde de la carte principale.",
            "insufficient_balance" to "Solde insuffisant",
            "addon_issued" to "Carte supplémentaire émise",
            "continue" to "Continuer",
            "addon_cards" to "Cartes d'extension",
            "no_addon_cards" to "Pas de cartes d'extension",
            "addon_card_badge" to "ADDON CARD"
        ),
        "es" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "Mis Tarjetas",
            "apply_new" to "Solicitar Nueva",
            "logout" to "Cerrar sesión",
            "settings" to "Ajustes",
            "language" to "Idioma",
            "select_language" to "Seleccionar Idioma",
            "action_required" to "Acción Requerida",
            "awaiting_payment" to "Esperando Pago",
            "pay_now" to "Pagar Ahora",
            "apply_for_card" to "Solicitar Nueva Tarjeta",
            "back" to "Atrás",
            "current_balance" to "Saldo Actual",
            "transactions" to "Transacciones",
            "deposits" to "Depósitos",
            "deposit_crypto" to "Depositar Cripto",
            "address_copied" to "Dirección copiada",
            "card_payment" to "Pago con Tarjeta",
            "total_to_pay" to "Monto Total a Pagar",
            "deposit_address" to "Dirección de Depósito",
            "i_have_paid" to "He Pagado",
            "login" to "Iniciar sesión",
            "register" to "Registrarse",
            "email" to "Correo electrónico",
            "password" to "Contraseña",
            "dont_have_account" to "¿No tienes cuenta? Regístrate",
            "already_have_account" to "¿Ya tienes cuenta? Inicia sesión",
            "user_not_found" to "Usuario No Encontrado",
            "3ds_auth" to "Autenticación 3DS",
            "merchant" to "Comercio",
            "amount" to "Monto",
            "approve" to "Aprobar",
            "reject" to "Rechazar",
            "approved" to "Aprobado",
            "verify_details" to "Por favor verifique los detalles de la transacción antes de aprobar.",
            "disclaimer_non_usdc" to "Para monedas que no sean USDC, se aplican tarifas de depósito del 2% más las de la red. Tasas de cambio a USDC al valor real.",
            "disclaimer_exact_amount" to "Por favor pague el monto exacto solamente. Montos menores pueden causar pérdida de fondos. $5.00 permanecerán como saldo inicial.",
            "step_fee" to "Hay una tarifa por tarjetas nuevas de $%s de los cuales $5 permanecerán como saldo. Confirme para continuar.",
            "step_first_name" to "¿Cuál será el primer nombre en la tarjeta?",
            "step_last_name" to "¿Cuál será el apellido en la tarjeta?",
            "step_dob" to "¿Cuál es su fecha de nacimiento?",
            "step_country_code" to "¿Cuál es el código de teléfono de su país?",
            "step_phone" to "¿Cuál es su número de teléfono?",
            "step_address" to "¿Cuál es su dirección?",
            "step_city" to "¿En qué ciudad vive?",
            "step_state" to "¿En qué estado/provincia vive?",
            "step_country" to "¿En qué país vive?",
            "step_postal" to "¿Cuál es su código postal?",
            "thank_you_apply" to "Gracias, voy a solicitar la tarjeta para usted ahora.",
            "invalid_phone" to "Entrada no válida. El número de teléfono no debe incluir espacios ni caracteres especiales. Inténtelo de nuevo.",
            "confirm" to "Confirmar",
            "cancel" to "Cancelar",
            "apply" to "Solicitar",
            "done" to "Hecho",
            "search_country" to "Buscar País",
            "search_country_code" to "Buscar Código de País",
            "select_dob" to "Seleccionar Fecha de Nacimiento",
            "welcome_registered" to "¡Bienvenido! ¿Ya estás registrado?",
            "great_email" to "¡Genial! Ingrese su correo electrónico.",
            "now_password" to "Ahora, ingrese su contraseña.",
            "invalid_password_format" to "La contraseña debe tener 6 caracteres alfanuméricos. Inténtelo de nuevo.",
            "login_failed" to "Error al iniciar sesión",
            "enter_email" to "Ingrese correo...",
            "enter_password" to "Ingrese contraseña...",
            "reset_link_sent" to "Se ha enviado un enlace de restablecimiento si el correo está registrado.",
            "enter_email_first" to "Por favor, ingrese primero su correo en el chat.",
            "forgot_password" to "¿Olvidó su contraseña?",
            "yes" to "Sí",
            "no" to "No",
            "create_account" to "Crear Cuenta",
            "let_create_account" to "¡Vamos a crear tu cuenta! Ingrese su correo electrónico.",
            "choose_password" to "¡Genial! Ahora elija una contraseña (6 caracteres alfanuméricos).",
            "registration_failed" to "Error al registrarse",
            "card_details" to "Detalles de la Tarjeta",
            "cardholder" to "Titular",
            "addon_cardholder" to "Titular adicional",
            "expiry" to "Expira",
            "billing_address" to "Dirección de Facturación",
            "crypto_deposit" to "Depósito Cripto",
            "today" to "Hoy",
            "yesterday" to "Ayer",
            "approval_failed" to "Error en la aprobación. Inténtelo de nuevo.",
            "register_or_forgot" to "¿Registrarse o Olvidó su contraseña?",
            "virtual_card_for" to "Tarjeta virtual para %s",
            "virtual_card" to "Tarjeta virtual",
            "share_app" to "Compartir aplicación",
            "review_app" to "Calificar aplicación",
            "delete_account" to "Eliminar cuenta",
            "delete_disclaimer" to "Su cuenta se eliminará de inmediato, los detalles de las transacciones de su tarjeta se conservarán durante 2 años según lo exijan las políticas de prevención de lavado de dinero.",
            "are_you_sure" to "¿Está seguro?",
            "apply_addon" to "Aplicar Addon",
            "apply_for_addon" to "Solicitar tarjeta adicional",
            "addon_info" to "Las tarjetas adicionales utilizan el mismo saldo que la tarjeta principal. El cargo por la tarjeta adicional se deducirá del saldo de la tarjeta principal.",
            "insufficient_balance" to "Saldo insuficiente",
            "addon_issued" to "Tarjeta adicional emitida",
            "continue" to "Continue",
            "addon_cards" to "Tarjetas adicionales",
            "no_addon_cards" to "Sin tarjetas adicionales",
            "addon_card_badge" to "ADICIONAL"
        ),
        "th" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "บัตรของฉัน",
            "apply_new" to "สมัครบัตรใหม่",
            "logout" to "ออกจากระบบ",
            "settings" to "การตั้งค่า",
            "language" to "ภาษา",
            "select_language" to "เลือกภาษา",
            "action_required" to "ต้องดำเนินการ",
            "awaiting_payment" to "รอการชำระเงิน",
            "pay_now" to "ชำระเงินตอนนี้",
            "apply_for_card" to "สมัครบัตรใบใหม่",
            "back" to "กลับ",
            "current_balance" to "ยอดเงินปัจจุบัน",
            "transactions" to "รายการเดินบัญชี",
            "deposits" to "รายการฝาก",
            "deposit_crypto" to "ฝากคริปโต",
            "address_copied" to "คัดลอกที่อยู่แล้ว",
            "card_payment" to "การชำระเงินผ่านบัตร",
            "total_to_pay" to "ยอดเงินทั้งหมดที่ต้องชำระ",
            "deposit_address" to "ที่อยู่สำหรับฝากเงิน",
            "i_have_paid" to "ฉันชำระเงินแล้ว",
            "login" to "เข้าสู่ระบบ",
            "register" to "ลงทะเบียน",
            "email" to "อีเมล",
            "password" to "รหัสผ่าน",
            "dont_have_account" to "ยังไม่มีบัญชี? ลงทะเบียน",
            "already_have_account" to "มีบัญชีอยู่แล้ว? เข้าสู่ระบบ",
            "user_not_found" to "ไม่พบผู้ใช้",
            "3ds_auth" to "การยืนยันตัวตน 3DS",
            "merchant" to "ร้านค้า",
            "amount" to "จำนวนเงิน",
            "approve" to "อนุมัติ",
            "reject" to "ปฏิเสธ",
            "approved" to "อนุมัติแล้ว",
            "verify_details" to "โปรดตรวจสอบรายละเอียดรายการก่อนอนุมัติ",
            "disclaimer_non_usdc" to "สำหรับเหรียญที่ไม่ใช่ USDC จะมีค่าธรรมเนียมการฝาก 2% บวกค่าธรรมเนียมเครือข่าย อัตราแลกเปลี่ยนเป็น USDC ตามจริง",
            "disclaimer_exact_amount" to "โปรดชำระตามยอดที่ระบุเท่านั้น ยอดที่น้อยกว่าอาจทำให้เงินสูญหาย ยอดเงิน 5.00$ จะเป็นยอดเริ่มต้นในบัตร",
            "step_fee" to "มีค่าธรรมเนียมสมัครบัตรใหม่ %s$ โดย 5$ จะเป็นยอดเงินคงเหลือในบัตร ยืนยันเพื่อดำเนินการต่อ",
            "step_first_name" to "ชื่อจริงบนหน้าบัตรคืออะไร?",
            "step_last_name" to "นามสกุลบนหน้าบัตรคืออะไร?",
            "step_dob" to "วันเกิดของคุณคือวันที่เท่าไหร่?",
            "step_country_code" to "รหัสโทรศัพท์ประเทศของคุณคืออะไร?",
            "step_phone" to "เบอร์โทรศัพท์ของคุณคือเบอร์อะไร?",
            "step_address" to "ที่อยู่ของคุณคือที่ไหน?",
            "step_city" to "คุณอยู่อำเภอ/เขต อะไร?",
            "step_state" to "คุณอยู่จังหวัดอะไร?",
            "step_country" to "คุณอยู่ประเทศอะไร?",
            "step_postal" to "รหัสไปรษณีย์ของคุณคืออะไร?",
            "thank_you_apply" to "ขอบคุณ ฉันกำลังดำเนินการสมัครบัตรให้คุณ",
            "invalid_phone" to "ข้อมูลไม่ถูกต้อง เบอร์โทรศัพท์ไม่ควรมีช่องว่างหรือตัวอักษรพิเศษ โปรดระบุใหม่อีกครั้ง",
            "confirm" to "ยืนยัน",
            "cancel" to "ยกเลิก",
            "apply" to "สมัคร",
            "done" to "เสร็จสิ้น",
            "search_country" to "ค้นหาประเทศ",
            "search_country_code" to "ค้นหารหัสประเทศ",
            "select_dob" to "เลือกวันเกิด",
            "welcome_registered" to "ยินดีต้อนรับ! คุณลงทะเบียนแล้วหรือยัง?",
            "great_email" to "ยอดเยี่ยม! โปรดระบุอีเมลของคุณ",
            "now_password" to "ตอนนี้ โปรดระบุรหัสผ่านของคุณ",
            "invalid_password_format" to "รหัสผ่านต้องมี 6 หลัก เป็นตัวอักษรหรือตัวเลข โปรดลองอีกครั้ง",
            "login_failed" to "เข้าสู่ระบบไม่สำเร็จ",
            "enter_email" to "ระบุอีเมล...",
            "enter_password" to "ระบุรหัสผ่าน...",
            "reset_link_sent" to "หากอีเมลนี้ลงทะเบียนไว้ ลิงก์รีเซ็ตรหัสผ่านจะถูกส่งไป",
            "enter_email_first" to "โปรดระบุอีเมลของคุณในแชทก่อน",
            "forgot_password" to "ลืมรหัสผ่าน?",
            "yes" to "ใช่",
            "no" to "ไม่",
            "create_account" to "สร้างบัญชี",
            "let_create_account" to "มาสร้างบัญชีกันเถอะ! โปรดระบุอีเมลของคุณ",
            "choose_password" to "ยอดเยี่ยม! ตอนนี้เลือกรหัสผ่าน (6 หลัก ตัวอักษรหรือตัวเลข)",
            "registration_failed" to "ลงทะเบียนไม่สำเร็จ",
            "card_details" to "รายละเอียดบัตร",
            "cardholder" to "ชื่อผู้ถือบัตร",
            "addon_cardholder" to "ชื่อผู้ถือบัตรเสริม",
            "expiry" to "วันหมดอายุ",
            "billing_address" to "ที่อยู่เรียกเก็บเงิน",
            "crypto_deposit" to "ฝากคริปโต",
            "today" to "วันนี้",
            "yesterday" to "เมื่อวาน",
            "approval_failed" to "การอนุมัติล้มเหลว โปรดลองอีกครั้ง",
            "register_or_forgot" to "ลงทะเบียน หรือ ลืมรหัสผ่าน?",
            "virtual_card_for" to "บัตรเสมือนสำหรับ %s",
            "virtual_card" to "บัตรเสมือน",
            "share_app" to "แชร์แอป",
            "review_app" to "รีวิวแอป",
            "delete_account" to "ลบบัญชี",
            "delete_disclaimer" to "บัญชีของคุณจะถูกลบทันที ข้อมูลธุรกรรมบัตรของคุณจะถูกเก็บไว้เป็นเวลา 2 ปีตามที่กำหนดโดยนโยบาย AML",
            "are_you_sure" to "คุณแน่ใจหรือไม่?",
            "apply_addon" to "สมัคร Addon",
            "apply_for_addon" to "สมัครบัตรเสริม",
            "addon_info" to "บัตรเสริมจะใช้ยอดเงินร่วมกับบัตรหลัก โดยค่าธรรมเนียมสำหรับบัตรเสริมจะถูกหักออกจากยอดเงินคงเหลือในบัตรหลัก",
            "insufficient_balance" to "ยอดเงินไม่เพียงพอ",
            "addon_issued" to "ออกบัตรเสริมเรียบร้อยแล้ว",
            "continue" to "ดำเนินการต่อ",
            "addon_cards" to "บัตรเสริม",
            "no_addon_cards" to "ไม่มีบัตรเสริม",
            "addon_card_badge" to "บัตรเสริม"
        ),
        "pt" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "Meus Cartões",
            "apply_new" to "Solicitar Novo",
            "logout" to "Sair",
            "settings" to "Configurações",
            "language" to "Idioma",
            "select_language" to "Selecionar Idioma",
            "action_required" to "Ação Necessária",
            "awaiting_payment" to "Aguardando Pagamento",
            "pay_now" to "Pagar Agora",
            "apply_for_card" to "Solicitar Novo Cartão",
            "back" to "Voltar",
            "current_balance" to "Saldo Atual",
            "transactions" to "Transações",
            "deposits" to "Depósitos",
            "deposit_crypto" to "Depositar Cripto",
            "address_copied" to "Endereço copiado",
            "card_payment" to "Pagamento com Cartão",
            "total_to_pay" to "Valor Total a Pagar",
            "deposit_address" to "Endereço de Depósito",
            "i_have_paid" to "Já Paguei",
            "login" to "Entrar",
            "register" to "Registrar",
            "email" to "E-mail",
            "password" to "Senha",
            "dont_have_account" to "Não tem conta? Registre-se",
            "already_have_account" to "Já tem conta? Entre",
            "user_not_found" to "Usuário Não Encontrado",
            "3ds_auth" to "Autenticação 3DS",
            "merchant" to "Estabelecimento",
            "amount" to "Valor",
            "approve" to "Aprovar",
            "reject" to "Rejeitar",
            "approved" to "Aprovado",
            "verify_details" to "Verifique os detalhes da transação antes de aprovar.",
            "disclaimer_non_usdc" to "Para moedas não-USDC, aplicam-se taxas de depósito de 2% mais taxas de rede. Taxas de câmbio para USDC conforme o valor real.",
            "disclaimer_exact_amount" to "Pague apenas o valor exato. Valores menores podem resultar em perda de fundos. $5.00 permanecerão como saldo inicial.",
            "step_fee" to "Há uma taxa de $%s para novos cartões, dos quais $5 permanecerão como saldo. Confirme para continuar.",
            "step_first_name" to "Qual será o primeiro nome no cartão?",
            "step_last_name" to "Qual será o sobrenome no cartão?",
            "step_dob" to "Qual é a sua data de nascimento?",
            "step_country_code" to "Qual é o código de telefone do seu país?",
            "step_phone" to "Qual é o seu número de telefone?",
            "step_address" to "Qual é o seu endereço?",
            "step_city" to "Qual é a sua cidade?",
            "step_state" to "Qual é o seu estado/provίνcia?",
            "step_country" to "Qual é o seu país?",
            "step_postal" to "Qual é o seu código postal?",
            "thank_you_apply" to "Obrigado, vou solicitar o cartão para você agora.",
            "invalid_phone" to "Entrada inválida. O número de telefone não deve incluir espaços ou caracteres especiais. Tente novamente.",
            "confirm" to "Confirmar",
            "cancel" to "Cancelar",
            "apply" to "Solicitar",
            "done" to "Concluído",
            "search_country" to "Buscar País",
            "search_country_code" to "Buscar Código",
            "select_dob" to "Selecionar Data de Nascimento",
            "welcome_registered" to "Bem-vindo! Você já é registrado?",
            "great_email" to "Ótimo! Digite seu e-mail.",
            "now_password" to "Agora, digite sua senha.",
            "invalid_password_format" to "A senha deve ter 6 caracteres alfanuméricos. Tente novamente.",
            "login_failed" to "Falha ao entrar",
            "enter_email" to "Digite o e-mail...",
            "enter_password" to "Digite a senha...",
            "reset_link_sent" to "Um link de redefinição foi enviado se o e-mail estiver registrado.",
            "enter_email_first" to "Digite seu e-mail no chat primeiro.",
            "forgot_password" to "Esqueceu a senha?",
            "yes" to "Sim",
            "no" to "Não",
            "create_account" to "Criar Conta",
            "let_create_account" to "Vamos criar sua conta! Digite seu e-mail.",
            "choose_password" to "Ótimo! Agora escolha uma senha (6 caracteres alfanuméricos).",
            "registration_failed" to "Falha ao registrar",
            "card_details" to "Detalhes do Cartão",
            "cardholder" to "Titular",
            "addon_cardholder" to "Titular adicional",
            "expiry" to "Validade",
            "billing_address" to "Endereço de Cobrança",
            "crypto_deposit" to "Depósito Cripto",
            "today" to "Hoje",
            "yesterday" to "Ontem",
            "approval_failed" to "Falha na aprovação. Tente novamente.",
            "register_or_forgot" to "Registrar ou Esqueceu a senha?",
            "virtual_card_for" to "Cartão virtual para %s",
            "virtual_card" to "Cartão virtual",
            "share_app" to "Compartilhar aplicativo",
            "review_app" to "Avaliar aplicativo",
            "delete_account" to "Excluir conta",
            "delete_disclaimer" to "Sua conta será excluída imediatamente, os detalhes das transações do seu cartão serão mantidos por 2 anos, conforme exigido pelas políticas de AML.",
            "are_you_sure" to "Você tem certeza?",
            "apply_addon" to "Aplicar Addon",
            "apply_for_addon" to "Solicitar cartão adicional",
            "addon_info" to "Os cartões adicionais utilizam o mesmo saldo que o cartão principal. A taxa do cartão adicional será deduzida do saldo do cartão principal.",
            "insufficient_balance" to "Saldo insuficiente",
            "addon_issued" to "Cartão adicional emitido",
            "continue" to "Continuar",
            "addon_cards" to "Cartões de extensão",
            "no_addon_cards" to "Sem cartões de extensão",
            "addon_card_badge" to "ADICIONAL"
        ),
        "ht" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "Kat Mwen Yo",
            "apply_new" to "Aplike pou nèf",
            "logout" to "Dekonekte",
            "settings" to "Anviwònman",
            "language" to "Lang",
            "select_language" to "Chwazi Lang",
            "action_required" to "Aksyon Obligatwa",
            "awaiting_payment" to "Ap Tann Peman",
            "pay_now" to "Peye Kounye a",
            "apply_for_card" to "Mande yon Nouvo Kat",
            "back" to "Retounen",
            "current_balance" to "Balans Kounye a",
            "transactions" to "Tranzaksyon",
            "deposits" to "Depo",
            "deposit_crypto" to "Depoze Kripto",
            "address_copied" to "Adrès kopye",
            "card_payment" to "Peman ak Kat",
            "total_to_pay" to "Kantite Total pou Peye",
            "deposit_address" to "Adrès Depo",
            "i_have_paid" to "Mwen te Peye",
            "login" to "Konekte",
            "register" to "Enskri",
            "email" to "Imèl",
            "password" to "Modpas",
            "dont_have_account" to "Ou pa gen kont? Enskri",
            "already_have_account" to "Ou gen kont deja? Konekte",
            "user_not_found" to "Itilizatè pa jwenn",
            "3ds_auth" to "Otantifikasyon 3DS",
            "merchant" to "Komèsan",
            "amount" to "Kantite",
            "approve" to "Apwouve",
            "reject" to "Rejte",
            "approved" to "Apwouve deja",
            "verify_details" to "Tanpri verifye detay tranzaksyon an anvan ou apwouve.",
            "disclaimer_non_usdc" to "Pou pyès ki pa USDC, gen frè depo 2% plis frè rezo. To echanj USDC se sa ki reyèl la.",
            "disclaimer_exact_amount" to "Tanpri peye kantite egzak la sèlman. Mwens kantite ka fè w pèdi lajan an. $5.00 ap rete kòm balans sou kat la.",
            "step_fee" to "Gen yon frè $%s pou nouvo kat, nan sa $5 ap rete kòm balans ou. Konfime pou kontinye.",
            "step_first_name" to "Ki premye non ki pral sou kat la?",
            "step_last_name" to "Ki dènye non ki pral sou kat la?",
            "step_dob" to "Ki dat ou te fèt?",
            "step_country_code" to "Ki kòd telefòn peyi w?",
            "step_phone" to "Ki nimewo telefòn ou?",
            "step_address" to "Ki adrès ou?",
            "step_city" to "Nan ki vil ou rete?",
            "step_state" to "Nan ki leta/pwovens ou rete?",
            "step_country" to "Nan ki peyi ou rete?",
            "step_postal" to "Ki kòd postal ou?",
            "thank_you_apply" to "Mèsi, mwen pral mande kat la pou ou kounye a.",
            "invalid_phone" to "Enfòmasyon pa bon. Nimewo telefòn lan pa dwe gen espas oswa karaktè espesyal. Refè l ankò.",
            "confirm" to "Konfime",
            "cancel" to "Anile",
            "apply" to "Aplike",
            "done" to "Fini",
            "search_country" to "Chèche Peyi",
            "search_country_code" to "Chèche Kòd Peyi",
            "select_dob" to "Chwazi Dat Nesans",
            "welcome_registered" to "Byenveni! Èske w enskri deja?",
            "great_email" to "Trè byen! Tanpri antre imèl ou.",
            "now_password" to "Kounye a, tanpri antre modpas ou.",
            "invalid_password_format" to "Modpas la dwe gen 6 karaktè (lèt ak nimewo). Tanpri reseye.",
            "login_failed" to "Koneksyon an echwe",
            "enter_email" to "Antre imèl...",
            "enter_password" to "Antre modpas...",
            "reset_link_sent" to "Yon lyen pou chanje modpas voye si imèl sa enskri.",
            "enter_email_first" to "Tanpri antre imèl ou nan chat la anvan.",
            "forgot_password" to "Bliye modpas?",
            "yes" to "Wi",
            "no" to "Non",
            "create_account" to "Kreye yon Kont",
            "let_create_account" to "Ann kreye kont ou! Tanpri antre imèl ou.",
            "choose_password" to "Trè byen! Kounye a chwazi yon modpas (6 karaktè lèt ak nimewo).",
            "registration_failed" to "Enskripsyon an echwe",
            "card_details" to "Detay Kat la",
            "cardholder" to "Mèt Kat la",
            "addon_cardholder" to "Mèt Kat anplis",
            "expiry" to "Ekspirasyon",
            "billing_address" to "Adrès Faktirasyon",
            "crypto_deposit" to "Depo Kripto",
            "today" to "Jodi a",
            "yesterday" to "Yè",
            "approval_failed" to "Apwobasyon an echwe. Tanpri reseye.",
            "register_or_forgot" to "Enskri oswa Bliye modpas?",
            "virtual_card_for" to "Kat vityèl pou %s",
            "virtual_card" to "Kat vityèl",
            "share_app" to "Pataje aplikasyon an",
            "review_app" to "Evalye aplikasyon an",
            "delete_account" to "Efase kont",
            "delete_disclaimer" to "Kont ou ap efase imedyatman, detay tranzaksyon kat ou yo ap konsève pou 2 zan jan politik AML mande sa.",
            "are_you_sure" to "Èske ou sèten?",
            "apply_addon" to "Aplike Addon",
            "apply_for_addon" to "Mande yon kat anplis",
            "addon_info" to "Kat anplis yo sèvi ak menm balans ak kat prensipal la. Frè pou kat anplis la ap dedui nan balans kat prensipal la.",
            "insufficient_balance" to "Balans pa ase",
            "addon_issued" to "Kat anplis la bay",
            "continue" to "Kontinye",
            "addon_cards" to "Kat ekstansyon",
            "no_addon_cards" to "Pa gen kat ekstansyon",
            "addon_card_badge" to "ANPLIS"
        ),
        "nl" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "Mijn Kaarten",
            "apply_new" to "Nieuwe Aanvragen",
            "logout" to "Uitloggen",
            "settings" to "Instellingen",
            "language" to "Taal",
            "select_language" to "Selecteer Taal",
            "action_required" to "Actie Vereist",
            "awaiting_payment" to "Wachten op Betaling",
            "pay_now" to "Nu Betalen",
            "apply_for_card" to "Nieuwe Kaart Aanvragen",
            "back" to "Terug",
            "current_balance" to "Huidig Saldo",
            "transactions" to "Transacties",
            "deposits" to "Stortingen",
            "deposit_crypto" to "Crypto Storten",
            "address_copied" to "Adres gekopieerd",
            "card_payment" to "Kaartbetaling",
            "total_to_pay" to "Totaal te Betalen",
            "deposit_address" to "Stortingsadres",
            "i_have_paid" to "Ik Heb Betaald",
            "login" to "Inloggen",
            "register" to "Registreren",
            "email" to "E-mail",
            "password" to "Wachtwoord",
            "dont_have_account" to "Geen account? Registreer",
            "already_have_account" to "Al een account? Log in",
            "user_not_found" to "Gebruiker Niet Gevonden",
            "3ds_auth" to "3DS Authenticatie",
            "merchant" to "Winkelier",
            "amount" to "Bedrag",
            "approve" to "Goedkeuren",
            "reject" to "Afwijzen",
            "approved" to "Goedgekeurd",
            "verify_details" to "Controleer de transactiegegevens voordat u goedkeurt.",
            "disclaimer_non_usdc" to "Voor niet-USDC-munten geldt 2% stortingskosten plus netwerkkosten. Wisselkoersen naar USDC zijn actueel.",
            "disclaimer_exact_amount" to "Betaal alleen het exacte bedrag. Lagere bedragen kunnen leiden tot verlies van geld. $5.00 blijft over als beginsaldo.",
            "step_fee" to "Er is een vergoeding van $%s voor nieuwe kaarten, waarvan $5 als saldo overblijft. Bevestig om door te gaan.",
            "step_first_name" to "Wat is de voornaam op de kaart?",
            "step_last_name" to "Wat is de achternaam op de kaart?",
            "step_dob" to "Wat is uw geboortedatum?",
            "step_country_code" to "Wat is de landcode van uw telefoon?",
            "step_phone" to "Wat is uw telefoonnummer?",
            "step_address" to "Wat is uw adres?",
            "step_city" to "In welke stad woont u?",
            "step_state" to "In welke provincie woont u?",
            "step_country" to "In welk land woont u?",
            "step_postal" to "Wat is uw postcode?",
            "thank_you_apply" to "Bedankt, ik ga de kaart nu voor u aanvragen.",
            "invalid_phone" to "Ongeldige invoer. Het telefoonnummer mag geen spaties of speciale tekens bevatten. Probeer het opnieuw.",
            "confirm" to "Bevestigen",
            "cancel" to "Annuleren",
            "apply" to "Aanvragen",
            "done" to "Klaar",
            "search_country" to "Land Zoeken",
            "search_country_code" to "Landcode Zoeken",
            "select_dob" to "Selecteer Geboortedatum",
            "welcome_registered" to "Welkom! Bent u al geregistreerd?",
            "great_email" to "Geweldig! Voer uw e-mailadres in.",
            "now_password" to "Voer nu uw wachtwoord in.",
            "invalid_password_format" to "Wachtwoord moet 6 alfanumerieke tekens zijn. Probeer het opnieuw.",
            "login_failed" to "Inloggen mislukt",
            "enter_email" to "Voer e-mail in...",
            "enter_password" to "Voer wachtwoord in...",
            "reset_link_sent" to "Een herstellink is verzonden als het e-mailadres bekend is.",
            "enter_email_first" to "Voer eerst uw e-mailadres in de chat in.",
            "forgot_password" to "Wachtwoord vergeten?",
            "yes" to "Ja",
            "no" to "Nee",
            "create_account" to "Account Aanmaken",
            "let_create_account" to "Laten we uw account aanmaken! Voer uw e-mailadres in.",
            "choose_password" to "Geweldig! Kies nu een wachtwoord (6 alfanumerieke tekens).",
            "registration_failed" to "Registratie mislukt",
            "card_details" to "Kaartgegevens",
            "cardholder" to "Kaarthouder",
            "addon_cardholder" to "Extra kaarthouder",
            "expiry" to "Vervaldatum",
            "billing_address" to "Factuuradres",
            "crypto_deposit" to "Crypto Storting",
            "today" to "Vandaag",
            "yesterday" to "Gisteren",
            "approval_failed" to "Goedkeuring mislukt. Probeer het opnieuw.",
            "register_or_forgot" to "Registreren of Wachtwoord vergeten?",
            "virtual_card_for" to "Virtuele kaart voor %s",
            "virtual_card" to "Virtuele kaart",
            "share_app" to "App delen",
            "review_app" to "App beoordelen",
            "delete_account" to "Account verwijderen",
            "delete_disclaimer" to "Uw account wordt onmiddellijk verwijderd, uw kaarttransactiegegevens worden gedurende 2 jaar bewaard zoals vereist door het AML-beleid.",
            "are_you_sure" to "Weet u het zeker?",
            "apply_addon" to "Addon toepassen",
            "apply_for_addon" to "Extra kaart aanvragen",
            "addon_info" to "Extra kaarten gebruiken hetzelfde saldo als de hoofdkaart. De kosten voor de extra kaart worden afgetrokken van het saldo van de hoofdkaart.",
            "insufficient_balance" to "Onvoldoende saldo",
            "addon_issued" to "Extra kaart uitgegeven",
            "continue" to "Doorgaan",
            "addon_cards" to "Add-on kaarten",
            "no_addon_cards" to "Geen add-on kaarten",
            "addon_card_badge" to "EXTRA"
        ),
        "he" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "הכרטיסים שלי",
            "apply_new" to "הזמנת חדש",
            "logout" to "התנתקות",
            "settings" to "הגדרות",
            "language" to "שפה",
            "select_language" to "בחירת שפה",
            "action_required" to "נדרשת פעולה",
            "awaiting_payment" to "ממתין לתשלום",
            "pay_now" to "שלם עכשיו",
            "apply_for_card" to "בקשת כרטיס חדש",
            "back" to "חזור",
            "current_balance" to "יתרה נוכחית",
            "transactions" to "עסקאות",
            "deposits" to "הפקדות",
            "deposit_crypto" to "הפקדת קריפטו",
            "address_copied" to "הכתובת הועתקה",
            "card_payment" to "תשלום בכרטיס",
            "total_to_pay" to "סה\"כ לתשלום",
            "deposit_address" to "כתובת להפקדה",
            "i_have_paid" to "שילמתי",
            "login" to "התחברות",
            "register" to "הרשמה",
            "email" to "אימייל",
            "password" to "סיסמה",
            "dont_have_account" to "אין לך חשבון? הירשם",
            "already_have_account" to "כבר יש לך חשבון? התחבר",
            "user_not_found" to "משתמש לא נמצא",
            "3ds_auth" to "אימות 3DS",
            "merchant" to "בית עסק",
            "amount" to "סכום",
            "approve" to "אשר",
            "reject" to "דחה",
            "approved" to "אושר",
            "verify_details" to "אנא ודא את פרטי העסקה לפני האישור.",
            "disclaimer_non_usdc" to "עבור מטבעות שאינם USDC, חלה עמלת הפקדה של 2% בתוספת עמלות רשת. שערי החליפין ל-USDC הם לפי הערך בפועל.",
            "disclaimer_exact_amount" to "אנא שלם את הסכום המדויק בלבד. סכומים נמוכים יותר עלולים לגרום לאובדן הכספים. $5.00 יישארו כיתרה ראשונית.",
            "step_fee" to "ישנה עמלה עבור כרטיסים חדשים בסך $%s מתוכם $5 יישארו כיתרה שלך. אשר להמשך.",
            "step_first_name" to "מה יהיה השם הפרטי על הכרטיס?",
            "step_last_name" to "מה יהיה שם המשפחה על הכרטיס?",
            "step_dob" to "מהו תאריך הלידה שלך?",
            "step_country_code" to "מהו קידומת הטלפון של המדינה שלך?",
            "step_phone" to "מהו מספר הטלפון שלך?",
            "step_address" to "מהי הכתובת שלך?",
            "step_city" to "באיזו עיר אתה גר?",
            "step_state" to "באיזה מחוז/מדינה אתה גר?",
            "step_country" to "באיזו מדינה אתה גר?",
            "step_postal" to "מהו המיקוד שלך?",
            "thank_you_apply" to "תודה, אני הולך לבקש את הכרטיס עבורך עכשיו.",
            "invalid_phone" to "קלט לא תקין. מספר הטלפון לא צריך לכלול רווחים או תווים מיוחדים. אנא נסה שוב.",
            "confirm" to "אישור",
            "cancel" to "ביטול",
            "apply" to "הגש בקשה",
            "done" to "בוצע",
            "search_country" to "חיפוש מדינה",
            "search_country_code" to "חיפוש קידומת",
            "select_dob" to "בחר תאריך לידה",
            "welcome_registered" to "ברוך הבא! האם אתה כבר רשום?",
            "great_email" to "נהדר! אנא הזן את כתובת האימייל שלך.",
            "now_password" to "עכשיו, אנא הזן את הסיסמה שלך.",
            "invalid_password_format" to "הסיסמה חייבת לכלול 6 תווים אלפאנומריים. אנא נסה שוב.",
            "login_failed" to "התחברות נכשלה",
            "enter_email" to "הזן אימייל...",
            "enter_password" to "הזן סיסמה...",
            "reset_link_sent" to "קישור לאיפוס נשלח אם האימייל רשום.",
            "enter_email_first" to "אנא הזן תחילה את האימייל שלך בצ'אט.",
            "forgot_password" to "שכחת סיסמה?",
            "yes" to "כן",
            "no" to "לא",
            "create_account" to "יצירת חשבון",
            "let_create_account" to "בוא ניצור את החשבון שלך! אנא הזן את כתובת האימייל שלך.",
            "choose_password" to "נהדר! עכשיו בחר סיסמה (6 תווים אלפאנומריים).",
            "registration_failed" to "הרשמה נכשלה",
            "card_details" to "פרטי כרטיס",
            "cardholder" to "בעל הכרטיס",
            "addon_cardholder" to "בעל כרטיס נוסף",
            "expiry" to "תוקף",
            "billing_address" to "כתובת לחיוב",
            "crypto_deposit" to "הפקדת קריפטו",
            "today" to "היום",
            "yesterday" to "אתמול",
            "approval_failed" to "האישור נכשל. אנא נסה שוב.",
            "register_or_forgot" to "הרשמה או שכחת סיסמה?",
            "virtual_card_for" to "כרטיס וירטואלי עבור %s",
            "virtual_card" to "כרטיס וירטואלי",
            "share_app" to "שתף אפליקציה",
            "review_app" to "דרג אפליקציה",
            "delete_account" to "מחיקת חשבון",
            "delete_disclaimer" to "חשבונך יימחק לאלתר, פרטי עסקאות הכרטיס שלך יישמרו למשך שנתיים כנדרש על פי מדיניות AML.",
            "are_you_sure" to "האם אתה בטוח?",
            "apply_addon" to "הוספת Addon",
            "apply_for_addon" to "בקשה לכרטיס נוסף",
            "addon_info" to "כרטיסים נוספים משתמשים באותה יתרה של הכרטיס הראשי. העמלה עבור הכרטיס הנוסף תנוכה מיתרת הכרטיס הראשי.",
            "insufficient_balance" to "אין יתרה מספקת",
            "addon_issued" to "הונפק כרטיס נוסף",
            "continue" to "המשך",
            "addon_cards" to "כרטיסי תוספת",
            "no_addon_cards" to "אין כרטיסי תוספת",
            "addon_card_badge" to "נוסף"
        ),
        "ar" to mapOf(
            "app_name" to "WalletCards",
            "my_cards" to "بطاقاتي",
            "apply_new" to "طلب جديد",
            "logout" to "تسجيل الخروج",
            "settings" to "الإعدادات",
            "language" to "اللغة",
            "select_language" to "اختر اللغة",
            "action_required" to "إجراء مطلوب",
            "awaiting_payment" to "بانتظار الدفع",
            "pay_now" to "ادفع الآن",
            "apply_for_card" to "طلب بطاقة جديدة",
            "back" to "رجوع",
            "current_balance" to "الرصيد الحالي",
            "transactions" to "المعاملات",
            "deposits" to "الإيداعات",
            "deposit_crypto" to "إيداع كريبتو",
            "address_copied" to "تم نسخ العنوان",
            "card_payment" to "الدفع بالبطاقة",
            "total_to_pay" to "المبلغ الإجمالي للدفع",
            "deposit_address" to "عنوان الإيداع",
            "i_have_paid" to "لقد دفعت",
            "login" to "تسجيل الدخول",
            "register" to "تسجيل",
            "email" to "البريد الإلكتروني",
            "password" to "كلمة المرور",
            "dont_have_account" to "ليس لديك حساب؟ سجل الآن",
            "already_have_account" to "لديك حساب بالفعل؟ سجل دخولك",
            "user_not_found" to "المستخدم غير موجود",
            "3ds_auth" to "مصادقة 3DS",
            "merchant" to "التاجر",
            "amount" to "المبلغ",
            "approve" to "موافقة",
            "reject" to "رفض",
            "approved" to "تمت الموافقة",
            "verify_details" to "يرجى التحقق من تفاصيل المعاملة قبل الموافقة.",
            "disclaimer_non_usdc" to "بالنسبة للعملات بخلاف USDC، تطبق رسوم إيداع 2٪ بالإضافة إلى رسوم الشبكة. أسعار الصرف إلى USDC هي بالقيم الفعلية.",
            "disclaimer_exact_amount" to "يرجى دفع المبلغ المحدد فقط. المبالغ الأقل قد تؤدي إلى فقدان الأموال. سيبقى 5.00 دولار كرصيد أولي للبطاقة.",
            "step_fee" to "هناك رسوم للبطاقات الجديدة قدرها %s$ سيبقى منها 5$ كرصيد لك. أكد للمتابعة.",
            "step_first_name" to "ما هو الاسم الأول الذي سيظهر على البطاقة؟",
            "step_last_name" to "ما هو اسم العائلة الذي سيظهر على البطاقة؟",
            "step_dob" to "ما هو تاريخ ميلادك؟",
            "step_country_code" to "ما هو رمز الاتصال الدولي لبلدك؟",
            "step_phone" to "ما هو رقم هاتفك؟",
            "step_address" to "ما هو عنوانك؟",
            "step_city" to "في أي مدينة تسكن؟",
            "step_state" to "في أي ولاية/محافظة تسكن؟",
            "step_country" to "في أي بلد تسكن؟",
            "step_postal" to "ما هو الرمز البريدي؟",
            "thank_you_apply" to "شكراً لك، سأقوم بطلب البطاقة لك الآن.",
            "invalid_phone" to "إدخال غير صحيح. يجب ألا يتضمن رقم الهاتف أي مسافات أو رموز خاصة. يرجى المحاولة مرة أخرى.",
            "confirm" to "تأكيد",
            "cancel" to "إلغاء",
            "apply" to "طلب",
            "done" to "تم",
            "search_country" to "بحث عن بلد",
            "search_country_code" to "بحث عن رمز بلد",
            "select_dob" to "اختر تاريخ الميلاد",
            "welcome_registered" to "مرحباً! هل أنت مسجل بالفعل؟",
            "great_email" to "رائع! يرجى إدخال بريدك الإلكتروني.",
            "now_password" to "الآن، يرجى إدخال كلمة المرور الخاصة بك.",
            "invalid_password_format" to "يجب أن تتكون كلمة المرور من 6 أحرف أو أرقام. يرجى المحاولة مرة أخرى.",
            "login_failed" to "فشل تسجيل الدخول",
            "enter_email" to "أدخل البريد الإلكتروني...",
            "enter_password" to "أدخل كلمة المرور...",
            "reset_link_sent" to "تم إرسال رابط إعادة التعيين إذا كان البريد مسجلاً.",
            "enter_email_first" to "يرجى إدخال بريدك الإلكتروني في الدردشة أولاً.",
            "forgot_password" to "نسيت كلمة المرور؟",
            "yes" to "نعم",
            "no" to "لا",
            "create_account" to "إنشاء حساب",
            "let_create_account" to "لنقم بإنشاء حسابك! يرجى إدخال بريدك الإلكتروني.",
            "choose_password" to "رائع! الآن اختر كلمة مرور (6 أحرف أو أرقام).",
            "registration_failed" to "فشل التسجيل",
            "card_details" to "تفاصيل البطاقة",
            "cardholder" to "حامل البطاقة",
            "addon_cardholder" to "حامل البطاقة الإضافية",
            "expiry" to "تاريخ الانتهاء",
            "billing_address" to "عنوان الفواتير",
            "crypto_deposit" to "إيداع كريبتو",
            "today" to "اليوم",
            "yesterday" to "أمس",
            "approval_failed" to "فشل المواพقة. يرجى المحاولة مرة أخرى.",
            "register_or_forgot" to "تسجيل أو نسيت كلمة المرور؟",
            "virtual_card_for" to "بطاقة افتراضية لـ %s",
            "virtual_card" to "بطاقة افتراضية",
            "share_app" to "مشاركة التطبيق",
            "review_app" to "تقييم التطبيق",
            "delete_account" to "حذف الحساب",
            "delete_disclaimer" to "سيتم حذف حسابك على الفور، وسيتم الاحتفاظ بتفاصيل معاملات بطاقتك لمدة عامين كما تقتضي سياسات مكافحة غسل الأموال.",
            "are_you_sure" to "هل أنت متأكد؟",
            "apply_addon" to "إضافة بطاقة",
            "apply_for_addon" to "طلب بطاقة إضافية",
            "addon_info" to "تستخدم البطاقات الإضافية نفس رصيد البطاقة الأساسية. سيتم خصم رسوم البطاقة الإضافية من رصيد البطاقة الأساسية.",
            "insufficient_balance" to "الرصيد غير كافٍ",
            "addon_issued" to "تم إصدار البطاقة الإضافية",
            "continue" to "استمرار",
            "addon_cards" to "بطاقات إضافية",
            "no_addon_cards" to "لا توجد بطاقات إضافية",
            "addon_card_badge" to "إضافي"
        )
    )

    fun getString(key: String): String {
        val lang = if (selectedLanguage.isEmpty()) "en" else selectedLanguage
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
